calorie/urls.py
from django.urls import path
from . import views

app_name = 'calorie'

urlpatterns = [
    path('foods/', views.food_list, name='food_list'),
    path('food/<int:pk>/', views.food_detail, name='food_detail'),
    path('summary/', views.daily_summary, name='daily_summary'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include('pages.urls')),
    path("dietplan/",include('dietplan.urls')),
    path("workoutplan/", include('workoutplan.urls')),
    path('exercises/', include('exercises.urls')),
    path('calorie/', include('calorie.urls')),
    path('articles/', include('articles.urls', namespace='articles')), 
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

dietplan/urls.py
from django.urls import path
from .views import ActivityLevelView, DietGoalView, DietPlanView, UpdateDietPlanView,DownloadDietPlanPDF

app_name = "dietplan"

urlpatterns = [
    path('goal/',DietGoalView.as_view(), name='goal' ),
    path("activity/", ActivityLevelView.as_view(), name='activity'),
    path('plan/',DietPlanView.as_view(), name='plan'),
    path('update/',UpdateDietPlanView.as_view(), name='update_plan' ),
    path('download-pdf/',DownloadDietPlanPDF.as_view(), name='download_pdf'),
]

exercises/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import MuscleViewSet, ExerciseViewSet, MuscleListView, MuscleDetailView

app_name = 'exercises'

router = DefaultRouter()
router.register('muscles', MuscleViewSet, basename='api_muscle')
router.register('exercises', ExerciseViewSet, basename='api_exercise')

urlpatterns = [
    path('muscles/', MuscleListView.as_view(), name='muscles_list'),
    path('muscles/<int:pk>/', MuscleDetailView.as_view(), name='muscle_detail'),
    # API endpoints
    path('api/', include(router.urls)),
]

pages/urls.py
from django.urls import path
from .views import HomePageView

app_name = "pages"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

workoutplan/urls.py
from django.urls import path
from .views import WorkoutGoalView, ExperienceLevelView, WorkoutPlanView, UpdateWorkoutPlanView , DownloadWorkoutPlanPDF, ChangePlanSessionView

app_name = 'workoutplan'

urlpatterns = [
    path('goal/',WorkoutGoalView.as_view(), name='goal'),
    path('experience/',ExperienceLevelView.as_view(), name='experience'),
    path('plan/',WorkoutPlanView.as_view(), name='workoutplan'),
    path('update/',UpdateWorkoutPlanView.as_view(), name='update'),
    path('download-pdf/',DownloadWorkoutPlanPDF.as_view(), name='download_pdf'),
    path('change-session/',ChangePlanSessionView.as_view(), name='change_sessions'),
]

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>{% block title %}Power{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
    
    {% load static %}
    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://unpkg.com/@phosphor-icons/web"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/icofont/dist/icofont.min.css">

    {% block extra_css %}{% endblock %}
</head>

<body class="{% block body_class %}{% endblock %}">

    {% comment %} <!-- Messages -->
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %} {% endcomment %}

    <!-- Header -->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">
            <a href="" class="logo d-flex align-items-center me-auto me-lg-0">
                <h1 class="sitename">Power Pulse</h1>
                <span>.</span>
            </a>

            <nav id="navmenu" class="navmenu">
                <ul>
                    <li><a href="{% url "pages:home" %}" class="{% block nav_home_active %}{% endblock %}">Home</a></li>
                    <li><a href="#about" class="{% block nav_about_active %}{% endblock %} scroll-to">About</a></li>
                    <li><a href="" class="{% block nav_services_active %}{% endblock %}">Services</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="">Profile</a></li>
                        <li><a href="{% url "account_logout" %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url "account_login" %}">Login</a></li>
                        <li><a href="{% url "account_signup" %}">Sign Up</a></li>
                    {% endif %}
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>
            {% load custom_filters %}
            {% if user.is_authenticated %}
                <div class="welcome-message">
                    <span style="color: #ffc451;">Welcome, {{ user.username|first_part }}!</span>
                </div>
            {% else %}
                <a class="btn-getstarted" href="{% url 'account_login' %}">Get Started</a>
            {% endif %}
        </div>
    </header>

    <main class="main">
        {% block content %}{% endblock %}
    </main>

    <!-- Footer -->
    <footer id="footer" class="footer dark-background">
        <div class="footer-top">
            <div class="container">
                <div class="row gy-4">
                    <div class="col-lg-4 col-md-6 footer-about">
                        <a href="" class="logo d-flex align-items-center">
                            <span class="sitename">Power Pulse</span>
                        </a>
                        <div class="footer-contact pt-3">
                            <p>iran, Boroujerd</p>
                            <p><strong>Email:</strong> <span>manisasani2005@gmail.com</span></p>
                        </div>
                        <div class="social-links d-flex mt-4">
                            <a href="https://t.me/ManiSasani"><i class="bi bi-telegram"></i></a>
                            <a href="https://www.instagram.com/manisasanii/"><i class="bi bi-instagram"></i></a>
                            <a href="https://www.linkedin.com/in/manisasani/"><i class="bi bi-linkedin"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-3 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <a href="">Home</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="">About us</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="">Services</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="">Terms of service</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="">Privacy policy</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="copyright">
            <div class="container text-center">
                <p>© <span>Copyright</span> <strong class="px-1 sitename">Power Pulse</strong> <span>All Rights Reserved</span></p>
            </div>
        </div>
    </footer>

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>

    <!-- Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/_base_clean.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
    
    <!-- Icons -->
    <script src="https://unpkg.com/@phosphor-icons/web"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    
    <!-- Common Form Styles -->
    <link href="{% static 'css/form_styles.css' %}" rel="stylesheet">
    
    <!-- Animation -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
    
    {% block extra_css %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">
    {% block content %}{% endblock %}
    
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
    {% block extra_scripts %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "_base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    <!-- Hero Section -->
    <section id="hero" class="hero section dark-background">
      <img src="{% static 'assets/img/mainhome.jpg' %}" alt="" data-aos="fade-in">
      <div class="container">
        <div class="row justify-content-center text-center" data-aos="fade-up" data-aos-delay="100">
          <div class="col-xl-6 col-lg-8">
            <h2>PowerPlus to build your ideal body<span>.</span></h2>
            <p>Your journey to a stronger you starts here</p>
          </div>
        </div>

        <div class="row gy-4 mt-5 justify-content-center" data-aos="fade-up" data-aos-delay="200">
          <div class="col-xl-2 col-md-4" data-aos="fade-up" data-aos-delay="300">
            <div class="icon-box">
              <i class="icofont-fast-food" style="font-size: 45px;"></i>
              <h3><a href="{% url "dietplan:activity" %}">Diet Plan</a></h3>
            </div>
          </div>
          <div class="col-xl-2 col-md-4" data-aos="fade-up" data-aos-delay="400">
            <div class="icon-box">
              <i class="ph ph-barbell" style="font-size: 45px;"></i>
              <h3><a href="{% url "workoutplan:goal" %}">Workout Plan</a></h3>
            </div>
          </div>
          <div class="col-xl-2 col-md-4" data-aos="fade-up" data-aos-delay="500">
            <div class="icon-box">
              <i class="icofont-gym-alt-3" style="font-size: 45px;"></i>
              <h3><a href="{% url 'exercises:muscles_list' %}">Exercises</a></h3>
            </div>
          </div>
          <div class="col-xl-2 col-md-4" data-aos="fade-up" data-aos-delay="600">
            <div class="icon-box">
              <i class="bi bi-calculator"></i>
              <h3><a href="{% url 'calorie:food_list' %}">Calorie counter</a></h3>
            </div>
          </div>
          <div class="col-xl-2 col-md-4" data-aos="fade-up" data-aos-delay="700">
            <div class="icon-box">
              <i class="bi bi-card-list"></i>
              <h3><a href="{% url 'articles:home' %}">Articles</a></h3>
            </div>
          </div>
        </div>
      </div> 
    </section>
    <!-- /Hero Section -->
    <!-- About Section -->
    <section id="about" class="about section dark-background">
      <div class="container" data-aos="fade-up" data-aos-delay="100">
        <div class="row gy-4">
          <div class="col-lg-6">
            <div class="content" style="padding: 20px 40px; margin-right: 30px;">
              <h3 style="margin-bottom: 20px; color: white;">Build the Best Version of Yourself!</h3>
              <p class="fst-italic" style="margin-bottom: 25px; color: #cccccc;">
                It's time to make a change! With expert training and nutrition plans, find the right path and get closer to your goal.
              </p>
              <ul style="margin-bottom: 30px;">
                <li style="margin-bottom: 15px; color: white;"><i class="bi bi-check2-all"></i> 
                  <span>Personalized workout plans based on your goals and fitness level</span>
                </li>
                <li style="margin-bottom: 15px; color: white;"><i class="bi bi-check2-all"></i> 
                  <span>Science-based nutrition for faster fat loss and muscle gain</span>
                </li>
                <li style="margin-bottom: 15px; color: white;"><i class="bi bi-check2-all"></i> 
                  <span>Step-by-step exercise guides with detailed video tutorials</span>
                </li>
              </ul>
              <p style="margin-top: 20px; color: white;">
                What are you waiting for? Start today, stay committed, and transform your body. With discipline and the right plan, you can become stronger, healthier, and more confident than ever!
              </p>
            </div>
          </div>
            <div class="col-lg-6 d-flex align-items-center justify-content-center">
              <div class="image-container">
                <img src="{% static 'assets/img/bamsted.jpg' %}" class="img-fluid" alt="">
              </div>
            </div>
        </div>
      </div>
    </section>
    <!-- About Section -->
    <!-- Testimonials Section -->
    <section id="testimonials" class="testimonials section dark-background">

      <img src="{% static 'assets/img/sakhtemon.jpg' %}" class="testimonials-bg" alt="">

      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="swiper init-swiper">
          <script type="application/json" class="swiper-config">
            {
              "loop": true,
              "speed": 600,
              "autoplay": {
                "delay": 5000
              },
              "slidesPerView": "auto",
              "pagination": {
                "el": ".swiper-pagination",
                "type": "bullets",
                "clickable": true
              }
            }
          </script>
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src="{% static 'assets/img/manisasani.jpg' %}" class="testimonial-img" alt="">
                <h3>Mani Sasani</h3>
                <h4>developer</h4>
                <div class="stars">
                  <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                    class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i>
                </div>
                <p>
                  <i class="bi bi-quote quote-icon-left"></i>
                  <span>Hi, I'm Mani, the creator of this website. My goal was to provide an excellent experience for users,
                     and I'd be happy to hear your feedback!.</span>
                  <i class="bi bi-quote quote-icon-right"></i>
                </p>
              </div>
{% endblock %}